language: node_js
node_js:
  - "11"
  
env:
  - DOCKER_COMPOSE_VERSION=1.8.0
  
services:
  - docker
  
install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - cd ./studio 
  - rm -rf ./node_mules/*
  - rm package-lock.json
  - npm install 
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker --version
  - docker-compose --version
  - cd ..
  - pwd
  - ls -la
  - docker-compose build
  - docker-compose up -d
  
